name: Hammercan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#66ff33'
    - '#3b941b'
    - '#215410'
    - '#68ce45'
  brandStrength: 1
  lightness: 0.4397616251371801
  saturation: 0.7744531538337469
  rhythmicContrast: 0.5484256180934608
purpose: []
